spring.application.name=WebServices

server.port=1907

spring.datasource.url=jdbc:postgresql://localhost:5432/quanlythuctap
spring.datasource.username=postgres
spring.datasource.password=1907
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chạy data.sql để seed dữ liệu Role
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

cloudinary.cloud-name=duwsd0fls
cloudinary.api-key=557828165226383
cloudinary.api-secret=QUNLJcGAQ6MwMbPdpnNmX5BUgoA

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret-key=your-very-long-secret-key-at-least-256-bits-for-hs256-algorithm-here123456
# Access token: 1 giờ (3600000ms)
jwt.expired=3600000
# Refresh token: 7 ngày (604800000ms)
jwt.refresh-expired=604800000
